#!/bin/bash

LUA="/usr/bin/lua"

# get lua version
VERSION=$("${LUA}" -v 2>&1 | cut --only-delimited --delimiter=\  --fields=2\
	| grep -o -E "[0-9]+\.[0-9]+")

# Execute th-lua[jit] script
"${LUA}" "/usr/share/lua/${VERSION}/trepl/th" "$@"
